# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_speakermodel_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakermodel',
            name='label',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
